references:
  defaults: &defaults
    docker:
      - image: circleci/node:10
        environment:
          TZ: "/usr/share/zoneinfo/Asia/Tokyo"
          LANG: ja_JP.UTF-8
          LC_ALL: C.UTF-8
          LANGUAGE: ja_JP.UTF-8
          DEPLOY_BRANCH: master
    working_directory: ~/app

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build
          command: |
            npm run build
            npm run generate
      - persist_to_workspace:
          root: ~/app
          paths:
            - ./dist
            - ./.git
      - save_cache:
          key: v-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: extract dist files
          command: |
            mv ./dist/* .
            rm -rf dist
      - run:
          name: add .nojekyll
          command: touch .nojekyll
      - run:
          name: ssh-keyscan
          command: |
            mkdir ~/.ssh
            touch ~/.ssh/known_hosts
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: push gh-pages
          command: |
            git config user.name 'circleci'
            git config user.email 'deploy@circleci.com'
            git add .
            git commit -m 'gh publish'
            git checkout -B gh-pages
            git push -u origin gh-pages --force

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
