version: 2

defaults: &defauls
  working_directory: ~/app
  docker:
    - image: circleci/node:10
      environment:
        TZ: "/usr/share/zoneinfo/Asia/Tokyo"
        LANG: ja_JP.UTF-8
        LC_ALL: C.UTF-8
        LANGUAGE: ja_JP.UTF-8
        DEPLOY_BRANCH: master

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: # 追加
          key: v-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build
          command: npm build
      - save_cache:
          key: v-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
  deploy:
      - run:
          name: remove files and dirs which exclude `dist`
          command: |
            /bin/ls -A | grep -v -E '^(dist$|.git)' | xargs rm -rf
            mv ./dist/* ./
            rm -rf ./dist
      - run:
          name: push gh-pages
          command: |
            git config user.name 'circleci'
            git config user.email 'deploy@circleci.com'
            git add .
            git commit -m 'gh publish'
            git checkout -B gh-pages
            git push -u origin gh-pages --force

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
        filters:
          branches:
            only: master
      - deploy
        requires:
          - build
        filters:
          branches:
            only: master
